#!/usr/bin/env ruby
require_relative 'domain_crawler'

if ARGV[0]
  root_domain = ARGV[0]
  root_domain = "http://#{root_domain}" if !root_domain.start_with?("http")
  # Not sure which would have better results, 'http' or 'https'
  DomainCrawler.new(root_domain).inspect
else
  puts "Please enter a domain to crawl."
end